### ISSUE TITLE
Could I hard code which filtered decks to rebuild

### ISSUE THREAD

**Issue by sskpe500** [Arthaey/anki-rebuild-all#5]
Hello, Thank you so much for this add-on. 
I wanted to ask if it would be possible to hard code which filtered decks were to be rebuilt.
I have a pre-made deck that I give all my students that have 2 different groups of filtered decks. 
The first group of filtered decks ( Qty = 5 ) searches for the student selected tags and
the second group of filtered decks ( Qty = 50 ) searches for each of the remaining tags in the deck.
If it would be possible to rebuilt the first group only or the second group only would be ideal.
The first group of tags are higher in the deck and I have determined that they are processed before 
the second group of filtered decks. In other words if a note has tags from the first group and second group then it is placed in the first filtered deck. Knowing this I wondered if it could be coded to just perform the first 5 filtered decks or to skip the first 5 and do the rest.
Thank you for any ideas.

**Comment by Arthaey** [comment]
If you edit [line 19 of RebuildAll.py](https://github.com/Arthaey/anki-rebuild-all/blob/master/RebuildAll.py#L19), where it says:

```
dynDeckIds = [ d["id"] for d in mw.col.decks.all() if d["dyn"] ]
```

Change the list of dynamic (aka filtered) deck IDs to be just the ones you want to rebuild. You can either use the card browser to figure out the filtered decks' IDs, or you can write some Python code to find them by name.
